training:
  batch_size: 32
  epochs: 100000
  embed_learning_rate: 0.0001
  extract_learning_rate: 0.0002
  discriminator_learning_rate: 0.0001

  betas:
    - 0.5
    - 0.999
  alpha: 0.1
  beta: 1.0

paths:
  train_dir: "F:/UnetWMGAN_final/UnetWMGAN/dataset/tiny-imagenet-200/train"
  host_dir: "F:/UnetWMGAN_final/UnetWMGAN/dataset/tiny-imagenet-200/train/host"
  watermark_dir: "F:/UnetWMGAN_final/UnetWMGAN/dataset/tiny-imagenet-200/train/watermark/images"
  save_dir: "./generated_images/generated_images_alpha=1_watermark_appointed"
  checkpoint_dir: "F:/UnetWMGAN_final/UnetWMGAN/checkpoints/checkpoints-alpha=1_host&watermark_appointed"

data:
  resize: [64, 64]
