training:
  batch_size: 32
  epochs: 100000
  embed_learning_rate: 0.0001
  extract_learning_rate: 0.0002
  discriminator_learning_rate: 0.0005

  betas:
    - 0.5
    - 0.999
  alpha: 0.1
  beta: 1.0

paths:
  train_dir: "F:/UnetWMGAN_final/UnetWMGAN/dataset/tiny-imagenet-200/banana2/images"
  save_dir: "./generated_images/alpha=0.1,beta=1.0_host&watermark_appointed_10x10000"
  checkpoint_dir: "F:/UnetWMGAN_final/UnetWMGAN/checkpoints/checkpoints-alpha=0.1,beta=1.0_host&watermark_appointed_10x10000"

data:
  resize: [64, 64]
